# Generated by Django 4.2.7 on 2023-12-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0002_alter_scrap_scrap_pic_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='scap',
            new_name='scrap',
        ),
    ]
